version: "3"
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: mysql:8
    volumes:
      - ~/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
